import wget

wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032806?fileName=ZCON_Holdings.csv&locale=en-CA", "BMO Conservative ETF_ZCON.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032807?fileName=ZBAL_Holdings.csv&locale=en-CA", "BMO Balanced ETF_ZBAL.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032808?fileName=ZGRO_Holdings.csv&locale=en-CA", "BMO Growth ETF_ZGRO.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156871?fileName=ZMI_Holdings.csv&locale=en-CA", "BMO Monthly Income ETF_ZMI.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1014041593?fileName=ZWC_Holdings.csv&locale=en-CA", "BMO Canadian High Dividend Covered Call ETF_ZWC.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156873?fileName=ZWB_Holdings.csv&locale=en-CA", "BMO Covered Call Canadian Banks ETF_ZWB.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032810?fileName=ZWK_Holdings.csv&locale=en-CA", "BMO Covered Call US Banks ETF_ZWK.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156886?fileName=ZWU_Holdings.csv&locale=en-CA", "BMO Covered Call Utilities ETF_ZWU.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156874?fileName=ZWA_Holdings.csv&locale=en-CA", "BMO Covered Call Dow Jones Industrial Average Hedged to CAD ETF_ZWA.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156852?fileName=ZWH_Holdings.csv&locale=en-CA", "BMO US High Dividend Covered Call ETF_ZWH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1022847840?fileName=ZWS_Holdings.csv&locale=en-CA", "BMO US High Dividend Covered Call Hedged to CAD ETF_ZWS.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1022847839?fileName=ZWP_Holdings.csv&locale=en-CA", "BMO Europe High Dividend Covered Call ETF_ZWP.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156855?fileName=ZWE_Holdings.csv&locale=en-CA", "BMO Europe High Dividend Covered Call Hedged to CAD ETF_ZWE.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156857?fileName=ZPW_Holdings.csv&locale=en-CA", "BMO US Put Write ETF_ZPW.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1014050435?fileName=ZPH_Holdings.csv&locale=en-CA", "BMO US Put Write Hedged to CAD ETF_ZPH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156836?fileName=ZCN_Holdings.csv&locale=en-CA", "BMO S&P-TSX Capped Composite Index ETF_ZCN.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156885?fileName=ZDV_Holdings.csv&locale=en-CA", "BMO Canadian Dividend ETF_ZDV.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156842?fileName=ZLB_Holdings.csv&locale=en-CA", "BMO Low Volatility Canadian Equity ETF_ZLB.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1020046299?fileName=ZVC_Holdings.csv&locale=en-CA", "BMO MSCI Canada Value Index ETF_ZVC.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156838?fileName=ZDJ_Holdings.csv&locale=en-CA", "BMO Dow Jones Industrial Average Hedged to CAD Index ETF_ZDJ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156844?fileName=ZSP_Holdings.csv&locale=en-CA", "BMO S&P 500 Index ETF_ZSP.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032805?fileName=ZNQ_Holdings.csv&locale=en-CA", "BMO NASDAQ 100 Equity Index ETF_ZNQ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156820?fileName=ZQQ_Holdings.csv&locale=en-CA", "BMO NASDAQ 100 Equity Hedged to CAD Index ETF_ZQQ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156837?fileName=ZUE_Holdings.csv&locale=en-CA", "BMO S&P 500 Hedged to CAD Index ETF_ZUE.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156831?fileName=ZUQ_Holdings.csv&locale=en-CA", "BMO MSCI USA High Quality Index ETF_ZUQ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156848?fileName=ZDY_Holdings.csv&locale=en-CA", "BMO US Dividend ETF_ZDY.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156878?fileName=ZUD_Holdings.csv&locale=en-CA", "BMO US Dividend Hedged to CAD ETF_ZUD.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156827?fileName=ZLU_Holdings.csv&locale=en-CA", "BMO Low Volatility US Equity ETF_ZLU.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156833?fileName=ZLH_Holdings.csv&locale=en-CA", "BMO Low Volatility US Equity Hedged to CAD ETF_ZLH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1020046303?fileName=ZEUS_Holdings.csv&locale=en-CA", "BMO Shiller Select US Index ETF_ZEUS.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1020046300?fileName=ZVU_Holdings.csv&locale=en-CA", "BMO MSCI USA Value Index ETF_ZVU.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1027206153?fileName=ZFC_Holdings.csv&locale=en-CA", "BMO SIA Focused Canadian Equity Fund ETF Series_ZFC.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1027206152?fileName=ZFN_Holdings.csv&locale=en-CA", "BMO SIA Focused North American Equity Fund ETF Series_ZFN.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1027500288?fileName=ZZZD_Holdings.csv&locale=en-CA", "BMO Tactical Dividend ETF Fund_ZZZD.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1024211828?fileName=WOMN_Holdings.csv&locale=en-CA", "BMO Women In Leadership Fund_WOMN.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156830?fileName=ZEA_Holdings.csv&locale=en-CA", "BMO MSCI EAFE Index ETF_ZEA.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156841?fileName=ZDM_Holdings.csv&locale=en-CA", "BMO MSCI EAFE Hedged to CAD Index ETF_ZDM.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156854?fileName=ZDI_Holdings.csv&locale=en-CA", "BMO International Dividend ETF_ZDI.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156856?fileName=ZDH_Holdings.csv&locale=en-CA", "BMO International Dividend Hedged to CAD ETF_ZDH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156835?fileName=ZLI_Holdings.csv&locale=en-CA", "BMO Low Volatility International Equity ETF_ZLI.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156832?fileName=ZLD_Holdings.csv&locale=en-CA", "BMO Low Volatility International Equity Hedged to CAD ETF_ZLD.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156845?fileName=ZEQ_Holdings.csv&locale=en-CA", "BMO MSCI Europe High Quality Hedged to CAD Index ETF_ZEQ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1020046302?fileName=ZVI_Holdings.csv&locale=en-CA", "BMO MSCI EAFE Value Index ETF_ZVI.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156816?fileName=ZEM_Holdings.csv&locale=en-CA", "BMO MSCI Emerging Markets Index ETF_ZEM.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002699047?fileName=ZLE_Holdings.csv&locale=en-CA", "BMO Low Volatility Emerging Markets Equity ETF_ZLE.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156826?fileName=ZGQ_Holdings.csv&locale=en-CA", "BMO MSCI All Country World High Quality Index ETF_ZGQ.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156818?fileName=ZCH_Holdings.csv&locale=en-CA", "BMO China Equity Index ETF_ZCH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156824?fileName=ZID_Holdings.csv&locale=en-CA", "BMO India Equity Index ETF_ZID.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156876?fileName=ZEB_Holdings.csv&locale=en-CA", "BMO Equal Weight Banks Index ETF_ZEB.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156840?fileName=ZEO_Holdings.csv&locale=en-CA", "BMO Equal Weight Oil & Gas Index ETF_ZEO.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156865?fileName=ZUT_Holdings.csv&locale=en-CA", "BMO Equal Weight Utilities Index ETF_ZUT.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156869?fileName=ZRE_Holdings.csv&locale=en-CA", "BMO Equal Weight REITs Index ETF_ZRE.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156843?fileName=ZIN_Holdings.csv&locale=en-CA", "BMO Equal Weight Industrials Index ETF_ZIN.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1028032804?fileName=ZHU_Holdings.csv&locale=en-CA", "BMO Equal Weight US Health Care Index ETF_ZHU.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156821?fileName=ZUH_Holdings.csv&locale=en-CA", "BMO Equal Weight U.S. Health Care Hedged to CAD Index ETF_ZUH.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156829?fileName=ZBK_Holdings.csv&locale=en-CA", "BMO Equal Weight U.S. Banks Index ETF_ZBK.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156846?fileName=ZUB_Holdings.csv&locale=en-CA", "BMO Equal Weight U.S. Banks Hedged to CAD Index ETF_ZUB.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156839?fileName=ZGI_Holdings.csv&locale=en-CA", "BMO Global Infrastructure Index ETF_ZGI.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156817?fileName=ZMT_Holdings.csv&locale=en-CA", "BMO Equal Weight Global Base Metals Hedged to CAD Index ETF_ZMT.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156825?fileName=ZGD_Holdings.csv&locale=en-CA", "BMO Equal Weight Global Gold Index ETF_ZGD.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1016047479?fileName=BANK_Holdings.csv&locale=en-CA", "BMO Global Banks Hedged to CAD Index ETF_BANK.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1016047482?fileName=INSR_Holdings.csv&locale=en-CA", "BMO Global Insurance Hedged to CAD Index ETF_INSR.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1016047480?fileName=DISC_Holdings.csv&locale=en-CA", "BMO Global Consumer Discretionary Hedged to CAD Index ETF_DISC.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1016047481?fileName=STPL_Holdings.csv&locale=en-CA", "BMO Global Consumer Staples Hedged to CAD Index ETF_STPL.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1023848504?fileName=COMM_Holdings.csv&locale=en-CA", "BMO Global Communications Index ETF_COMM.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156819?fileName=ZJG_Holdings.csv&locale=en-CA", "BMO Junior Gold Index ETF_ZJG.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156822?fileName=ZJO_Holdings.csv&locale=en-CA", "BMO Junior Oil Index ETF_ZJO.csv")
wget.download("https://api.kurtosys.io/tools/ksys317/api/download/csv/holding/1002156823?fileName=ZJN_Holdings.csv&locale=en-CA", "BMO Junior Gas Index ETF_ZJN.csv")